FROM python:3.13-slim

ARG BUILD_DEPS=" \
        build-essential \
        default-libmysqlclient-dev \
        pkg-config \
        python3-dev \
    "
RUN set -ex \
    && apt-get update \
    && apt-get install -y --no-install-recommends $BUILD_DEPS

RUN pip3 install --upgrade pip
COPY ./requirements.txt .
RUN pip3 install --no-cache-dir -r /requirements.txt

COPY ./database/django_populate_db_dev.sh .

ARG PROJECT_PATH=/django_project
RUN mkdir $PROJECT_PATH
WORKDIR $PROJECT_PATH
ADD src $PROJECT_PATH

ENV DJANGO_SETTINGS_MODULE=admin.settings

COPY entrypoint-dev.sh /entrypoint.sh
ENTRYPOINT  ["/entrypoint.sh"]
